### ISSUE TITLE
Non-docker run

### ISSUE THREAD

**Issue by tmshader** [Alexandre-P-J/GMeetRecorder#3]
Is it possible to run this without docker?

**Comment by Alexandre-P-J** [comment]
Both video and audio recording depend on X and Pulseaudio which are Linux software. Docker provides a Linux container that allows the project to run on any supported platform. A native version would require a different implementation for Linux, Windows and MacOS. And that is too much work.

If you really don't want to use Docker, you can run it on Linux but you need: 
- Software: pulseaudio, ffmpeg, xvfb, firefox
- Python3 modules: xvfbwrapper, selenium
- geckodriver binary in /usr/local/bin/geckodriver (you can run sources/get_geckodriver.sh to install it for you)

If you have all this, run sources/bot.py after setting all the ENV variables like you would normally do.

It's kinda sketchy... I recommend you use docker ;D

**Comment by Boffice** [comment]
when running in docker i get following error No PulseAudio daemon running, or not running as session daemon.
