### ISSUE TITLE
add heroku support 

### ISSUE THREAD

**Issue by ramanveerji** [Alexandre-P-J/GMeetRecorder#4]
add heroku support and option to do lecture/ meeting recording only

**Comment by Alexandre-P-J** [comment]
Sorry for the delay!
I'm not used to Heroku so I may need some time to evaluate if its possible. My biggest concern is that video encoring requires a decent amount of processing power.

**Comment by ramanveerji** [comment]
> Sorry for the delay!
> I'm not used to Heroku so I may need some time to evaluate if its possible. My biggest concern is that video encoring requires a decent amount of processing power.


No problem. Please try if possible. If It gets recorded and saved as video with the audio from the presenter, it would be very helpful. Please see if it is possible for saving the long calls in splits to reduce storage usage.

**Comment by Alexandre-P-J** [comment]
I've been trying to deploy the project on heroku but the required video compression limits its usage on the service notably. I guess a service that provides gpu or a cpu with video compression acceleration might be ideal, but tbh its out of the scope of the project for me to test it.
One benefit of the software being distributed as a docker container is that dependencies aren't a problem, so the deployment on whichever platform just works right away. I encourage you to try GMeetRecorder on aws, I guess a compute instance might be enough.

**Comment by ramanveerji** [comment]
> I've been trying to deploy the project on heroku but the required video compression limits its usage on the service notably. I guess a service that provides gpu or a cpu with video compression acceleration might be ideal, but tbh its out of the scope of the project for me to test it.
> One benefit of the software being distributed as a docker container is that dependencies aren't a problem, so the deployment on whichever platform just works right away. I encourage you to try GMeetRecorder on aws, I guess a compute instance might be enough.

There is another website called railway.app that helps to deploy apps. Can you try there?
