### ISSUE TITLE
Error: Attaching to gmeetrecorder-local-1 gmeetrecorder-local-1 exited with code 0

### ISSUE THREAD

**Issue by rahulvramesh** [Alexandre-P-J/GMeetRecorder#5]
hi guys, tried to run with Gmail as backend but got following error

Attaching to gmeetrecorder-local-1
gmeetrecorder-local-1 exited with code 0

Tried on mac m1 docker as well as linux system too.

**Comment by Alexandre-P-J** [comment]
I can't tell what's happening with the info you provided. Have you tried entering as a shell and running the command manually so you can check if the script is printing any useful information?

**Comment by lucazin** [comment]
for me too   vars  docker-compose up
